// 最終形の追加分（各地域で、実在12種＋ユニーク3種になるよう、実在8種＋ユニーク2種ずつ）。
// 大きさ・特徴は、日本語版Wikipedia（一部は英語版Wikipedia・日本語の情報サイト。確度B〜C）で確認した内容。出典はSPEC.mdに一覧がある。
// 架空の虫の説明文は、冒頭に「【架空の虫】」を付けている
import * as A from './bugArtMore';
import * as G from './bugArtGross';

export const EXTRA_INSECTS = [
  // ================= 日本 =================
  {
    id: 'jp_kokuwa',
    region: 'japan',
    name: 'コクワガタ',
    rarity: 'common',
    price: 10,
    sizeText: 'オス 1.8〜5.4cm／メス 2.2〜3.0cm（大あごを含む）',
    description: 'クワガタの中では庶民派。夜だけでなく、昼間も活動する働き者。オスの大あごに、歯が1つしかないのが目印。',
    grid: A.koKuwagata(),
  },
  {
    id: 'jp_aburazemi',
    region: 'japan',
    name: 'アブラゼミ',
    rarity: 'common',
    price: 10,
    sizeText: '約5.6〜6cm',
    description: '世界でも珍しい、はねが全部茶色くて不透明なセミ。「ジリジリ」と鳴いて、夏の暑さをいっそう暑苦しく盛り上げてくれる。',
    grid: A.aburazemi(),
  },
  {
    id: 'jp_okamakiri',
    region: 'japan',
    name: 'オオカマキリ',
    rarity: 'common',
    price: 12,
    sizeText: 'オス 7〜9cm／メス 8〜9.5cm以上',
    description: '前脚のつけ根に、黄色い点があるのが目印。泡のような卵鞘に、約200個もの卵を産みつける。子だくさんの、待ち伏せの名人。',
    grid: A.okamakiri(),
  },
  {
    id: 'jp_hirata',
    region: 'japan',
    name: 'ヒラタクワガタ',
    rarity: 'rare',
    price: 45,
    sizeText: 'オス 4.5〜9cm（本州のもの）／メス 2〜3.5cm',
    description: '平たくて黒い体で、木の洞にひそむのが得意。大あごの内側には、のこぎりのような小さな歯が並んでいる。',
    grid: A.hiratakuwagata(),
  },
  {
    id: 'jp_genji',
    region: 'japan',
    name: 'ゲンジボタル',
    rarity: 'rare',
    price: 50,
    sizeText: '約1.5cm',
    description: '日本のホタルの中では大きめ。胸には、黒い十字の模様がある。西日本では約2秒、東日本では約4秒おきに光る、ご当地リズムの持ち主。',
    grid: A.genjiBotaru(),
  },
  {
    id: 'jp_oniyanma',
    region: 'japan',
    name: 'オニヤンマ',
    rarity: 'rare',
    price: 55,
    sizeText: '全長 約9〜11cm',
    description: '日本最大のトンボ。黒と黄色のしま模様がトレードマーク。オスは川のなわばりを見回り、ほかのオスを追い払う、頼れる見張り役。',
    grid: A.oniyanma(),
  },
  {
    id: 'jp_tamamushi',
    region: 'japan',
    name: 'ヤマトタマムシ',
    rarity: 'epic',
    price: 160,
    sizeText: '約3〜4cm',
    description: '緑の金属光沢に、赤と緑のたてじま。昔は、その羽が法隆寺の玉虫厨子の飾りに使われた。「玉虫色」という言葉の由来でもある。',
    grid: A.yamatoTamamushi(),
  },
  {
    id: 'jp_omurasaki',
    region: 'japan',
    name: 'オオムラサキ',
    rarity: 'epic',
    price: 170,
    sizeText: '前翅長 約5〜5.5cm',
    description: '日本の国蝶。オスのはねは、鮮やかな青紫色。チョウなのに、花のみつだけでなく、クヌギなどの樹液も大好き。',
    grid: A.oomurasaki(),
  },
  {
    id: 'jp_kotatsu',
    region: 'japan',
    name: 'コタツムシ',
    rarity: 'unique',
    price: 130,
    sizeText: '約4cm（架空の虫）',
    description: '【架空の虫】冬になると、こたつから頭だけ出して動かなくなる。上にのせたみかんが、そのうち自分の仲間に見えてくる。',
    grid: A.kotatsuBug(),
  },
  {
    id: 'jp_hanabi',
    region: 'japan',
    name: 'ハナビムシ',
    rarity: 'unique',
    price: 140,
    sizeText: '約3cm（架空の虫）',
    description: '【架空の虫】夏祭りの夜に現れる、花火好きの虫。おしりの線香花火が消えると、なぜか急に静かになる。',
    grid: A.fireworkBug(),
  },

  // ================= ヨーロッパ =================
  {
    id: 'eu_mitsubachi',
    region: 'europe',
    name: 'セイヨウミツバチ',
    rarity: 'common',
    price: 10,
    sizeText: '働きバチ 約1.2〜1.4cm',
    description: '「8の字ダンス」で、花のある場所を仲間に教える。真夏の巣には、なんと4万〜8万匹も暮らしている。ちょっとした大都会である。',
    grid: A.seiyouMitsubachi(),
  },
  {
    id: 'eu_nanahoshi',
    region: 'europe',
    name: 'ナナホシテントウ',
    rarity: 'common',
    price: 10,
    sizeText: '約0.5〜0.9cm',
    description: '星は7つに見えるが、閉じたはねの合わせ目で、星が1つに合体している。危険を感じると、脚の関節から黄色くて臭い液を出す。',
    grid: A.nanahoshiTento(),
  },
  {
    id: 'eu_kujaku',
    region: 'europe',
    name: 'クジャクチョウ',
    rarity: 'common',
    price: 12,
    sizeText: 'はねを広げて約5.5cm',
    description: 'はねの目玉模様は、鳥などの天敵から身を守るためと考えられている。成虫のまま冬を越す、しぶとい越冬の名人。',
    grid: A.kujakuchou(),
  },
  {
    id: 'eu_usuba',
    region: 'europe',
    name: 'ウスバカマキリ',
    rarity: 'rare',
    price: 45,
    sizeText: 'オス 5.2〜6.6cm／メス 5.9〜6.6cm',
    description: 'ヨーロッパカマキリとも呼ばれる、世界でいちばん広く分布するカマキリ。前脚の内側に、黒い斑点がある。',
    grid: A.usubaKamakiri(),
  },
  {
    id: 'eu_apollo',
    region: 'europe',
    name: 'アポロウスバシロチョウ',
    rarity: 'rare',
    price: 50,
    sizeText: 'はねを広げて約7.5cm',
    description: '白い半透明のはねに、赤い丸い模様。標高1000〜2000mの、花のさく斜面が好き。高原のアイドル的存在。',
    grid: A.apolloChou(),
  },
  {
    id: 'eu_deathshead',
    region: 'europe',
    name: 'ヨーロッパメンガタスズメ',
    rarity: 'rare',
    price: 55,
    sizeText: 'はねを広げて約9〜12cm',
    description: '胸に、ドクロのような模様がある。危険を感じるとキイキイと鳴き、ミツバチの巣から蜂蜜をこっそり盗み飲む。見た目に反して、甘党。',
    grid: A.deathsHeadMoth(),
  },
  {
    id: 'eu_okujaku',
    region: 'europe',
    name: 'オオクジャクヤママユ',
    rarity: 'epic',
    price: 170,
    sizeText: 'はねを広げて約15〜20cm',
    description: 'ヨーロッパ最大のガ。名前は、クジャクの羽のような目玉模様にちなむ。ヤママユガの仲間は、成虫になると食事をとらず、つがいを探すことに全力を注ぐ。',
    grid: A.okujakuYamamayu(),
  },
  {
    id: 'eu_okashi',
    region: 'europe',
    name: 'オオカシカミキリ',
    rarity: 'epic',
    price: 180,
    sizeText: '約4.1〜5.5cm',
    description: 'オークの古木にすむ、ヨーロッパ最大級のカミキリムシ。オスの触角は、体より長い。国際自然保護連合（IUCN）のレッドリストで「危急種」とされ、EUの法律でも保護されている。',
    grid: A.ookashiKamikiri(),
  },
  {
    id: 'eu_cheese',
    region: 'europe',
    name: 'チーズムシ',
    rarity: 'unique',
    price: 130,
    sizeText: '約4cm（架空の虫）',
    description: '【架空の虫】穴あきチーズにそっくりな体。穴の数は、その日の気分で増えたり減ったりする（ということにしている）。',
    grid: A.cheeseBug(),
  },
  {
    id: 'eu_clock',
    region: 'europe',
    name: 'トケイムシ',
    rarity: 'unique',
    price: 150,
    sizeText: '約5cm（架空の虫）',
    description: '【架空の虫】時計台の形をした、時間にうるさい虫。ぴったり正午に鳴くが、たまに5分ずれる。それはご愛嬌。',
    grid: A.clockBug(),
  },

  // ================= 東南アジア =================
  {
    id: 'sea_oogomadara',
    region: 'sea',
    name: 'オオゴマダラ',
    rarity: 'common',
    price: 12,
    sizeText: 'はねを広げて約13cm',
    description: '日本のチョウとしては最大級。ゆっくり羽ばたき、フワフワと滑るように飛ぶ。幼虫は毒のある葉を食べ、その毒を体にためて身を守る。',
    grid: A.oogomadara(),
  },
  {
    id: 'sea_oomitsubachi',
    region: 'sea',
    name: 'オオミツバチ',
    rarity: 'common',
    price: 14,
    sizeText: '働きバチ 約1.7〜2cm',
    description: 'ミツバチの仲間なのに、スズメバチ並みの気の荒さ。木の枝や崖に、1枚の巨大な巣板をぶら下げる。大きな巣は、幅2mにもなる。',
    grid: A.oomitsubachi(),
  },
  {
    id: 'sea_himekabuto',
    region: 'sea',
    name: 'ヒメカブト',
    rarity: 'common',
    price: 12,
    sizeText: '約3.5〜7cm',
    description: '東南アジアに広く分布する、ごく普通のカブトムシ。日本のカブトムシの胸の角を引きのばしたような角で、相手をがっちり挟み込む。',
    grid: A.himekabuto(),
  },
  {
    id: 'sea_caucasus',
    region: 'sea',
    name: 'コーカサスオオカブト',
    rarity: 'rare',
    price: 50,
    sizeText: 'オス 7.5〜13.3cm／メス 4〜6.7cm',
    description: '頭に1本、胸に2本の、合わせて3本の角を持つ。前ばねは、青銅色や緑銅色など、角度で色が変わる金属光沢。',
    grid: A.caucasusBeetle(),
  },
  {
    id: 'sea_leafinsect',
    region: 'sea',
    name: 'コノハムシ',
    rarity: 'rare',
    price: 45,
    sizeText: 'メス 約10cm（大型の種の場合）',
    description: 'メスは、葉脈まで葉っぱそっくり。ジャングルで、風にゆれるふりをしてやり過ごす。オスは細長くて、まったく葉に似ていない。',
    grid: A.leafInsect(),
  },
  {
    id: 'sea_akaeri',
    region: 'sea',
    name: 'アカエリトリバネアゲハ',
    rarity: 'rare',
    price: 55,
    sizeText: 'はねを広げて約15〜17cm',
    description: 'マレーシアの国蝶。オスのはねは黒地で、電気のように光る緑の模様がある。学名は、サラワクの「ラジャ（王）」ブルックにちなむ。',
    grid: A.akaeriBirdwing(),
  },
  {
    id: 'sea_chan',
    region: 'sea',
    name: 'チャンズ・メガスティック',
    rarity: 'epic',
    price: 190,
    sizeText: '体長 約35cm（脚を伸ばした全長 約55cm）',
    description: 'ナナフシの中で最大（最長）とされる種。ボルネオ島で見つかった。名前は、標本を提供したチャンさんにちなむ。',
    grid: A.giantStick(),
  },
  {
    id: 'sea_goliathbird',
    region: 'sea',
    name: 'ゴライアストリバネアゲハ',
    rarity: 'epic',
    price: 200,
    sizeText: 'メスのはねは約21cm',
    description: 'アレクサンドラトリバネアゲハと並び、世界最大のチョウとして知られる。オスは、エメラルドグリーンと黄色が混じったはねを持つ。',
    grid: A.goliathBirdwing(),
  },
  {
    id: 'sea_tuktuk',
    region: 'sea',
    name: 'トゥクトゥクムシ',
    rarity: 'unique',
    price: 130,
    sizeText: '約4cm（架空の虫）',
    description: '【架空の虫】三輪の乗り物「トゥクトゥク」そっくりの虫。乗客はいないが、運転手（本人）は、いつも張り切っている。',
    grid: A.tuktukBug(),
  },
  {
    id: 'sea_durian',
    region: 'sea',
    name: 'ドリアンムシ',
    rarity: 'unique',
    price: 150,
    sizeText: '約5cm（架空の虫）',
    description: '【架空の虫】トゲトゲのドリアンにそっくり。果物の王様ぶっているが、においで、いつも先に存在を知られてしまう。',
    grid: A.durianBug(),
  },

  // ================= 南米 =================
  {
    id: 'am_gunta',
    region: 'amazon',
    name: 'グンタイアリ',
    rarity: 'common',
    price: 10,
    sizeText: '働きアリ 約1.5cm／女王 約2cm',
    description: '決まった巣を持たず、体をつなげて即席の橋やはしごをつくりながら行軍する。隊列は、最長20mになることもある。',
    grid: A.armyAnt(),
  },
  {
    id: 'am_heliconius',
    region: 'amazon',
    name: 'ヒョウモンドクチョウ',
    rarity: 'common',
    price: 12,
    sizeText: 'はねを広げて約7cm',
    description: 'アルゼンチン北部からアメリカ南部までの、熱帯にすむ。幼虫は、トケイソウの仲間を食べて育つ。',
    grid: A.hyomonDokuchou(),
  },
  {
    id: 'am_treehopper',
    region: 'amazon',
    name: 'ツノゼミ',
    rarity: 'common',
    price: 14,
    sizeText: '数mm〜約1cm（種によって違う）',
    description: '頭の上に、なぞの飾り（ヘルメット）が乗っている。樹液を吸い、余った甘い汁でアリを呼んで、守ってもらう。世界に約3200種もいる。',
    grid: A.treehopper(),
  },
  {
    id: 'am_stingless',
    region: 'amazon',
    name: 'ハリナシバチ',
    rarity: 'rare',
    price: 45,
    sizeText: '数mm〜約2cm（種による）',
    description: '針が退化して、刺せないハチ。巣の入口には、樹脂でできた小さなトンネルがある。中南米には、特にたくさんの仲間がいる。',
    grid: A.stinglessBee(),
  },
  {
    id: 'am_elephas',
    region: 'amazon',
    name: 'エレファスゾウカブト',
    rarity: 'rare',
    price: 50,
    sizeText: 'オス 7〜14.4cm／メス 5〜8.5cm',
    description: '金色のビロードのような毛が、体じゅうに生えている。メキシコからコロンビアにかけてすむ、ゾウカブトの仲間。',
    grid: A.elephasBeetle(),
  },
  {
    id: 'am_owl',
    region: 'amazon',
    name: 'フクロウチョウ',
    rarity: 'rare',
    price: 55,
    sizeText: 'はねを広げて約6.5〜20cm（種による）',
    description: 'はねの裏に、フクロウの目のような大きな模様。鳥などの天敵が少ない夕方に飛ぶ。発酵した果物が大好物。',
    grid: A.owlButterfly(),
  },
  {
    id: 'am_titan',
    region: 'amazon',
    name: 'タイタンオオウスバカミキリ',
    rarity: 'epic',
    price: 200,
    sizeText: '全長 16.5cm以上',
    description: '甲虫の中でも体積が最大級。成虫は食事をとらず、幼虫の時期は3年以上かかると考えられている。アマゾンの熱帯雨林にすむ。',
    grid: A.titanBeetle(),
  },
  {
    id: 'am_neptune',
    region: 'amazon',
    name: 'ネプチューンオオカブト',
    rarity: 'epic',
    price: 190,
    sizeText: 'オス 8〜16.5cm／メス 5〜7.3cm',
    description: '漆黒の体に、非常に細長い角。頭の角は、甲虫類としては最長とされる。胸の角の下には、オレンジ色のブラシ状の毛が生えている。',
    grid: A.neptuneBeetle(),
  },
  {
    id: 'am_lifting',
    region: 'amazon',
    name: 'リフティングムシ',
    rarity: 'unique',
    price: 130,
    sizeText: '約4cm（架空の虫）',
    description: '【架空の虫】ボールをリフティングし続ける虫。最高記録は、なぜか毎回「あと1回で新記録」らしい。',
    grid: A.liftingBug(),
  },
  {
    id: 'am_mate',
    region: 'amazon',
    name: 'マテチャムシ',
    rarity: 'unique',
    price: 140,
    sizeText: '約4cm（架空の虫）',
    description: '【架空の虫】ひょうたんのカップで、マテ茶をストローで飲む虫。一杯を、ゆっくり時間をかけて味わう主義。',
    grid: A.mateBug(),
  },

  // ================= アフリカ =================
  {
    id: 'af_driver',
    region: 'africa',
    name: 'サスライアリ',
    rarity: 'common',
    price: 10,
    sizeText: '働きアリ 約1.5cm〜／女王 最大約5cm',
    description: 'アフリカの熱帯雨林で、数十万から百万もの大きな群れをつくる。グンタイアリの仲間は、行軍のとき、みんなで体をつなげて橋になる。',
    grid: A.driverAnt(),
  },
  {
    id: 'af_tsetse',
    region: 'africa',
    name: 'ツェツェバエ',
    rarity: 'common',
    price: 12,
    sizeText: '約0.5〜1cm',
    description: 'アフリカにだけすむ、吸血するハエ。卵ではなく、お腹の中で育てた幼虫を産む、ちょっと変わった子育て。',
    grid: A.tsetse(),
  },
  {
    id: 'af_giraffeweevil',
    region: 'africa',
    name: 'キリンクビナガオトシブミ',
    rarity: 'common',
    price: 14,
    sizeText: '約2.5〜5cm',
    description: 'マダガスカルにだけすむ、首がやたら長い甲虫。オスの首は、メスの2〜3倍もある。名前のとおり、キリンのよう。',
    grid: A.giraffeWeevil(),
  },
  {
    id: 'af_eyedmantis',
    region: 'africa',
    name: 'アフリカメダマカマキリ',
    rarity: 'rare',
    price: 45,
    sizeText: 'メス 約4cm（オスは少し小さい）',
    description: '翅に、うずまきのような目玉模様がある。敵に見つかると、翅をパッと広げて、目玉で威嚇する。',
    grid: A.spinyFlowerMantis(),
  },
  {
    id: 'af_devilmantis',
    region: 'africa',
    name: 'デビルズフラワーマンティス',
    rarity: 'rare',
    price: 55,
    sizeText: 'メス 約13cm／オス 約10cm',
    description: '敵におどろかされると、前脚を立てて、赤・青・白・紫のはでな模様を見せて威嚇する。花に化ける名人として、最大級ともいわれる。',
    grid: A.devilFlowerMantis(),
  },
  {
    id: 'af_gladiator',
    region: 'africa',
    name: 'マントファスマ',
    rarity: 'rare',
    price: 50,
    sizeText: '約2cm',
    description: '「かかとで歩く」ように見えるので、日本語では「カカトアルキ」とも。2002年に、昆虫の31番目のグループとして発表された、生きた化石のような存在。',
    grid: A.gladiator(),
  },
  {
    id: 'af_centaurus',
    region: 'africa',
    name: 'ケンタウルスオオカブト',
    rarity: 'epic',
    price: 180,
    sizeText: 'オス 4〜8.5cm（角を含む）',
    description: 'アフリカでは唯一といわれる、大型のカブトムシ。頭の角と、先が分かれた胸の角が、ほぼ同じ長さ。',
    grid: A.centaurusBeetle(),
  },
  {
    id: 'af_comet',
    region: 'africa',
    name: 'コメットガ',
    rarity: 'epic',
    price: 200,
    sizeText: 'はねを広げて約20cm（尾は約15cm）',
    description: 'マダガスカルだけにすむ、長い尾のガ。成虫は口が使えず、6〜8日ほどの短い寿命で、つがいを探すことに全力を注ぐ。',
    grid: A.cometMoth(),
  },
  {
    id: 'af_safari',
    region: 'africa',
    name: 'サファリムシ',
    rarity: 'unique',
    price: 130,
    sizeText: '約5cm（架空の虫）',
    description: '【架空の虫】双眼鏡をのぞきながら、ジープでサバンナを走る虫。見つける動物より、自分が写真を撮られることのほうが多い。',
    grid: A.safariBug(),
  },
  {
    id: 'af_kilimanjaro',
    region: 'africa',
    name: 'キリマンジャロムシ',
    rarity: 'unique',
    price: 150,
    sizeText: '約6cm（架空の虫）',
    description: '【架空の虫】雪をかぶった山の形の虫。頂上には、いつも雲がかかっている。暑がりの旅人には、ありがたい存在。',
    grid: A.kilimanjaroBug(),
  },
  // ================= ちょっとグロテスクな有名生き物（各地域1種、南米は2種。エピック） =================
  {
    id: 'jp_jorogumo',
    region: 'japan',
    name: 'ジョロウグモ',
    rarity: 'epic',
    price: 150,
    sizeText: 'メス 1.7〜3.0cm／オス 0.6〜1.0cm（巣は直径1mほど）',
    description: '黄色と黒のしま模様が、ちょっと派手すぎる。巣の糸が光で金色に輝くので、夜道で顔に引っかかるとしばらく引きずる。毒はあるが、人にはほぼ無害。',
    grid: G.jorogumo(),
  },
  {
    id: 'eu_tarantula',
    region: 'europe',
    name: '本家タランチュラ',
    rarity: 'epic',
    price: 170,
    sizeText: 'メス 約2.7cm／オス 約1.9cm',
    description: '南イタリアのタラントの町にいたコモリグモが、「タランチュラ」の名の元祖。かまれると踊り続けると信じられたが、実際の毒は怖くない。名前だけ、大出世して世界へ。',
    grid: G.wolfSpider(),
  },
  {
    id: 'sea_tagame',
    region: 'sea',
    name: 'タイワンタガメ',
    rarity: 'epic',
    price: 160,
    sizeText: 'メス 7.4〜8.0cm／オス 6.4〜7.8cm',
    description: '水の中から、鎌のような前脚でカエルや魚をつかまえる。タイでは「メンダー」と呼ばれて食べられ、オスは青リンゴのような香りがして、市場で高く売られる。',
    grid: G.giantWaterBug(),
  },
  {
    id: 'am_birdeater',
    region: 'amazon',
    name: 'ゴライアスバードイーター',
    rarity: 'epic',
    price: 170,
    sizeText: '体長 約10cm（脚を広げると20cm超）',
    description: '世界最大級のタランチュラ。名前は「鳥を食べるもの」だが、実際に食べるのは、おもに昆虫やカエル。おしりの毛を蹴り飛ばして、敵を追い払う。',
    grid: G.birdEater(),
  },
  {
    id: 'am_centipede',
    region: 'amazon',
    name: 'ペルビアンジャイアントオオムカデ',
    rarity: 'epic',
    price: 180,
    sizeText: '通常 20〜30cm（最大40cm超）',
    description: '世界最大のムカデ。虫はもちろん、タランチュラやトカゲ、ときには小さなヘビまで襲う。見た目のわりに足は速く、夜中に出会うと心臓に悪い。',
    grid: G.giantCentipede(),
  },
  {
    id: 'af_scorpion',
    region: 'africa',
    name: 'エンペラースコーピオン',
    rarity: 'epic',
    price: 160,
    sizeText: '標準 12〜15cm（最大記録 22cm）',
    description: '皇帝の名をもつ、大きな黒いサソリ。はさみは立派だが、毒は弱い。紫外線（ブラックライト）を当てると、青緑にぼうっと光る。',
    grid: G.emperorScorpion(),
  },
];
